apiVersion: v2
name: qfc-node
description: QFC Blockchain Node Helm Chart
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - qfc
  - blockchain
  - validator
maintainers:
  - name: QFC Team
    email: dev@qfc.network
